load("//Config:buck_rule_macros.bzl", "framework")

framework(
    name = "Postbox",
    srcs = glob([
        "Sources/*.swift",
    ]),
    deps = [
    	"//submodules/Crc32:Crc32",
    	"//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
    	"//submodules/sqlcipher:sqlcipher",
        "//submodules/MurMurHash32:MurMurHash32",
        "//submodules/StringTransliteration:StringTransliteration",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/Security.framework",
    ],
)
