load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "ActivityIndicator",
    srcs = glob([
        "Sources/*.swift",
    ]),
    deps = [
    	"//submodules/TelegramPresentationData",
        "//submodules/AsyncDisplayKit",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
