load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "MurmurHash",
    srcs = glob([
        "Sources/**/*.swift",
        "Sources/**/*.m",
    ]),
    headers = glob([
        "Sources/**/*.h",
    ]),
    exported_headers = glob([
        "Sources/**/*.h",
    ]),
    deps = [
        "//submodules/Database/MurmurHash/Impl:MurMurHashObjC",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
