load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "WatchBridgeAudio",
    srcs = glob([
        "Sources/**/*.swift",
        "Sources/**/*.m",
        "Sources/**/*.mm",
    ]),
    headers = glob([
        "Sources/**/*.h",
    ], exclude = ["Sources/WatchBridgeAudio.h"]),
    exported_headers = glob([
        "Sources/**/*.h",
    ], exclude = ["Sources/WatchBridgeAudio.h"]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/SSignalKit/SSignalKit:SSignalKit",
        "//submodules/OpusBinding:OpusBinding",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/AVFoundation.framework",
        "$SDKROOT/System/Library/Frameworks/AudioToolbox.framework",
    ],
)
