load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "WatchBridgeAudio",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/WatchBridgeAudio/Impl:WatchBridgeAudioImpl",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/AVFoundation.framework",
        "$SDKROOT/System/Library/Frameworks/AudioToolbox.framework",
    ],
)
