load("//Config:buck_rule_macros.bzl", "framework")

framework(
    name = "SwiftSignalKit",
    srcs = glob([
        "Source/**/*.swift",
    ]),
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
