load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "SwiftSignalKit",
    module_name = "SwiftSignalKit",
    srcs = glob([
        "Source/**/*.swift",
    ]),
    visibility = [
        "//visibility:public",
    ],
)
