load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "MozjpegBinding",
    srcs = glob([
        "Sources/*.m",
    ]),
    headers = glob([
        "Sources/*.h",
    ]),
    exported_headers = glob([
        "Public/**/*.h",
    ]),
    deps = [
        "//third-party/mozjpeg:mozjpeg",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
