load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "UrlWhitelist",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
