language: objective-c
osx_image: xcode7.2

env:
  global:
    - PROJECT="Support/HockeySDK.xcodeproj"
    - SDK="iphonesimulator"
    - CONFIGURATION="DEBUG"

  matrix:
    - SCHEME="HockeySDK"             DESTINATION="OS=8.1,name=iPhone 5"                 RUN_TESTS="YES"
    - SCHEME="HockeySDK"             DESTINATION="OS=8.4,name=iPhone 6"                 RUN_TESTS="YES"
    - SCHEME="HockeySDK"             DESTINATION="OS=9.0,name=iPad Air"                 RUN_TESTS="YES"
    - SCHEME="HockeySDK"             DESTINATION="OS=9.0,name=iPhone 6 Plus"            RUN_TESTS="YES"
    - SCHEME="HockeySDK"             DESTINATION="OS=9.1,name=iPad Pro"                 RUN_TESTS="YES"
    - SCHEME="HockeySDK"             DESTINATION="OS=9.2,name=iPhone 6s"                RUN_TESTS="YES"
    - SCHEME="HockeySDK Framework"   DESTINATION="platform=iOS Simulator,name=iPhone 6" RUN_TESTS="YES"
    - SCHEME="HockeySDK Distribution"                                                   RUN_TESTS="NO"

before_install:
  - xcrun simctl list
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - COMMAND="xcodebuild -project '$PROJECT' -scheme '$SCHEME' -sdk '$SDK' -configuration '$CONFIGURATION'"
  - if [ $RUN_TESTS == "YES" ]; then
      COMMAND+=" -destination '$DESTINATION' XCODEBUILD_GCC_PREPROCESSOR_DEFINITIONS="CI=1" clean test";
    fi
  - COMMAND+=" | xcpretty -c"
  - echo $COMMAND
  - eval $COMMAND
