load('//tools:buck_utils.bzl', 'config_with_updated_linker_flags', 'configs_with_config', 'combined_config')
load('//tools:buck_defs.bzl', 'SHARED_CONFIGS', 'EXTENSION_LIB_SPECIFIC_CONFIG')

apple_library(
    name = 'TelegramApi',
    srcs = glob([
	    'Sources/*.swift',
    ]),
    configs = configs_with_config(combined_config([SHARED_CONFIGS, EXTENSION_LIB_SPECIFIC_CONFIG])),
    swift_compiler_flags = [
        '-suppress-warnings',
        '-application-extension',
    ],
    visibility = ['PUBLIC'],
    deps = [
    ],
    frameworks = [
		'$SDKROOT/System/Library/Frameworks/Foundation.framework',
    ],
)
