load("//Config:buck_rule_macros.bzl", "static_library")

apple_resource(
    name = "OverlayStatusControllerResources",
    files = glob([
        "Resources/**/*",
    ], exclude = ["Resources/**/.*"]),
    visibility = ["PUBLIC"],
)

static_library(
    name = "OverlayStatusController",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
    	"//submodules/Display:Display#shared",
        "//submodules/OverlayStatusController/Impl:OverlayStatusControllerImpl",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
