load("//Config:buck_rule_macros.bzl", "static_library")

apple_resource(
    name = "LegacyComponentsResources",
    dirs = [
        "Resources/LegacyComponentsResources.bundle",
    ],
    visibility = ["PUBLIC"],
)

static_library(
    name = "LegacyComponents",
    srcs = glob([
        "Sources/*.m",
        "Sources/*.mm",
        "Sources/*.c",
        "Sources/*.cpp",
    ]),
    headers = glob([
        "Sources/*.h",
    ]),
    exported_headers = glob([
        "PublicHeaders/**/*.h",
    ]),
    deps = [
        "//submodules/SSignalKit/SSignalKit:SSignalKit",
        "//submodules/AppBundle:AppBundle",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
    weak_frameworks = [
        "Vision",
    ],
)
