load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "ProgressNavigationButtonNode",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/ActivityIndicator:ActivityIndicator",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
