load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "AccountContext",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
    	"//submodules/TelegramAudio:TelegramAudio",
    	"//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
    	"//submodules/TemporaryCachedPeerDataManager:TemporaryCachedPeerDataManager",
    	"//submodules/DeviceLocationManager:DeviceLocationManager",
    	"//submodules/MediaPlayer:UniversalMediaPlayer",
    	"//submodules/TelegramPresentationData:TelegramPresentationData",
    	"//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
    	"//submodules/Postbox:Postbox#shared",
    	"//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/WalletCore:WalletCore",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
    weak_frameworks = [
        "Contacts",
    ],
)
