load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "AccountContext",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
    	"//submodules/TelegramAudio:TelegramAudio",
    	"//submodules/AsyncDisplayKit:AsyncDisplayKit#dynamic",
    	"//submodules/TemporaryCachedPeerDataManager:TemporaryCachedPeerDataManager",
    	"//submodules/DeviceLocationManager:DeviceLocationManager",
    	"//submodules/MediaPlayer:UniversalMediaPlayer",
    	"//submodules/TelegramPresentationData:TelegramPresentationData",
    	"//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#dynamic",
    	"//submodules/Postbox:Postbox#dynamic",
    	"//submodules/TelegramCore:TelegramCore#dynamic",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
    weak_frameworks = [
        "Contacts",
    ],
)
