load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "LegacyDataImport",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
	    "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
	    "//submodules/Postbox:Postbox#shared",
	    "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
    	"//submodules/TelegramNotices:TelegramNotices",
    	"//submodules/TelegramUIPreferences:TelegramUIPreferences",
    	"//submodules/RadialStatusNode:RadialStatusNode",
    	"//submodules/LegacyComponents:LegacyComponents",
        "//submodules/LegacyDataImport/Impl:LegacyDataImportImpl",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
