load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Lotties",
    module_name = "Lotties",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    copts = [
    ],
    deps = [
    ],
    visibility = [
        "//visibility:public",
    ],
)
