load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "PlatformRestrictionMatching",
    srcs = glob([
        "Sources/*.swift",
    ]),
    deps = [
        "//submodules/TelegramCore:TelegramCore#dynamic",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
