load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "TelegramVoip",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/Postbox:Postbox#shared",
    	"//submodules/TelegramUIPreferences:TelegramUIPreferences",
        "//submodules/TgVoip:TgVoip",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
