load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "QrCode",
    srcs = glob([
        "Sources/**/*.swift",
        "Sources/**/*.cpp",
    ]) + [
        "Sources/QrCodeInstance.mm"
    ],
    has_cpp = True,
    deps = [
    	"//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
    	"//submodules/Display:Display#shared",
    ],
    headers = glob([ 
        "Sources/**/*.hpp",
    ]) + [
        "Sources/QrCodeInstance.h"
    ],
    exported_headers = [
        "Sources/QrCodeInstance.h"
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
        "$SDKROOT/System/Library/Frameworks/CoreImage.framework",
    ],
)
