load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "LocationUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/TelegramCore:TelegramCore#shared",
    	"//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/LegacyComponents:LegacyComponents",
        "//submodules/ShareController:ShareController",
        "//submodules/AccountContext:AccountContext",
        "//submodules/OpenInExternalAppUI:OpenInExternalAppUI",
        "//submodules/LegacyUI:LegacyUI",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
        "$SDKROOT/System/Library/Frameworks/CoreLocation.framework",
    ],
)
