load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "Svg",
    srcs = glob([
        "Sources/**/*.m",
        "Sources/**/*.mm",
        "Sources/**/*.c",
        "Sources/**/*.cpp",
    ]),
    headers = glob([
        "Sources/**/*.h",
    ]),
    exported_headers = [
        "Sources/Svg.h",
    ],
)
