load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "PKCS",
    srcs = glob([
        "Sources/**/*.m",
    ]),
    headers = glob([
        "Sources/**/*.h",
    ]),
    exported_headers = glob([
        "PublicHeaders/**/*.h",
    ]),
    deps = [
        "//submodules/openssl:openssl",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
