load("//Config:configs.bzl",
    "app_binary_configs",
    "library_configs",
    "app_info_plist_substitutions",
    "DEVELOPMENT_LANGUAGE",
)

load("//Config:buck_rule_macros.bzl",
    "framework_binary_dependencies",
    "framework_bundle_dependencies",
    "glob_map",
    "glob_sub_map",
    "merge_maps",
)

framework_dependencies = [
    "//submodules/MtProtoKit:MtProtoKit",
    #"//submodules/Emoji:Emoji",
]

apple_library(
    name = "AppLibrary",
    visibility = [
        "//:",
        "//...",
    ],
    configs = library_configs(),
    swift_version = native.read_config("swift", "version"),
    srcs = [
        "Telegram-iOS/main.m",
        "Telegram-iOS/Application.swift"
    ],
    deps = [
        "//submodules/MtProtoKit:MtProtoKitFramework",
    ]
)

apple_binary(
    name = "AppBinary",
    visibility = [
        "//:",
        "//...",
    ],
    configs = app_binary_configs(),
    swift_version = native.read_config("swift", "version"),
    srcs = [
        "Empty.swift",
    ],
    deps = [
        ":AppLibrary",
    ]
)

apple_bundle(
    name = "Telegram",
    visibility = [
        "//:",
    ],
    extension = "app",
    binary = ":AppBinary",
    product_name = "Telegram",
    info_plist = "Telegram-iOS/Info.plist",
    info_plist_substitutions = app_info_plist_substitutions(),
    deps = [
        "//submodules/MtProtoKit:MtProtoKitFramework",
    ]
)

# Package

apple_package(
    name = "AppPackage",
    bundle = ":Telegram",
)

xcode_workspace_config(
    name = "workspace",
    workspace_name = "Telegram_Buck",
    src_target = ":Telegram",
)