load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "TonBinding",
    srcs = glob([
        "Sources/**/*.m",
    ]),
    headers = merge_maps([
        "Sources/**/*.h",
    ]),
    visibility = ["PUBLIC"],
    deps = [
        "//submodules/SSignalKit/SignalKit:SSignalKit",
        "//submodules/openssl:openssl",
        "//submodules/ton:ton",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
