load("//Config:buck_rule_macros.bzl", "static_library")

prebuilt_apple_framework(
    name = "CrashReporter",
    framework = "Vendor/CrashReporter.framework",
    preferred_linkage = "static",
)

static_library(
    name = "HockeySDK",
    srcs = glob([
        "Classes/*.m",
        "Classes/*.mm",
    ]),
    headers = glob([
        "Classes/*.h",
    ]),
    exported_headers = [
        "Classes/HockeySDKFeatureConfig.h",
        "Classes/HockeySDKEnums.h",
        "Classes/HockeySDKNullability.h",
        "Classes/BITAlertAction.h",

        "Classes/BITHockeyManager.h",

        "Classes/BITHockeyAttachment.h",

        "Classes/BITHockeyBaseManager.h",
        "Classes/BITCrashManager.h",
        "Classes/BITCrashAttachment.h",
        "Classes/BITCrashManagerDelegate.h",
        "Classes/BITCrashDetails.h",
        "Classes/BITCrashMetaData.h",

        "Classes/BITAuthenticator.h",

        "Classes/BITUpdateManager.h",
        "Classes/BITUpdateManagerDelegate.h",
        "Classes/BITUpdateViewController.h",
        "Classes/BITHockeyBaseViewController.h",
        "Classes/BITHockeyManagerDelegate.h",
    ],
    compiler_flags = [
        '-DBITHOCKEY_VERSION=@\"5.1.2\"',
        '-DBITHOCKEY_C_VERSION="5.1.2"',
        '-DBITHOCKEY_C_BUILD="108"',
        "-DHOCKEYSDK_FEATURE_CRASH_REPORTER=1",
        "-DHOCKEYSDK_FEATURE_UPDATES=1",
        "-DHOCKEYSDK_FEATURE_FEEDBACK=0",
        "-DHOCKEYSDK_FEATURE_AUTHENTICATOR=1",
        "-DHOCKEYSDK_FEATURE_METRICS=0",
    ],
    deps = [
        ":CrashReporter",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
