load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "GalleryData",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/AccountContext:AccountContext",
        "//submodules/AppBundle:AppBundle",
        "//submodules/PresentationDataUtils:PresentationDataUtils",
        "//submodules/InstantPageUI:InstantPageUI",
        "//submodules/GalleryUI:GalleryUI",
        "//submodules/PeerAvatarGalleryUI:PeerAvatarGalleryUI",
        "//submodules/MediaResources:MediaResources",
        "//submodules/WebsiteType:WebsiteType",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
        "$SDKROOT/System/Library/Frameworks/QuickLook.framework",
        "$SDKROOT/System/Library/Frameworks/SafariServices.framework",
    ],
)
