load("//Config:buck_rule_macros.bzl", "framework")

framework(
    name = "TelegramCore",
    srcs = glob([
        "TelegramCore/*.swift",
        "TelegramCore/*.m",
    ]),
    headers = [
        "TelegramCore/Crypto.h",
        "TelegramCore/NetworkLogging.h",
        "TelegramCore/Reachability.h",
    ],
    exported_headers = [
        "TelegramCore/Crypto.h",
        "TelegramCore/NetworkLogging.h",
        "TelegramCore/Reachability.h",
    ],
    deps = [
        "//submodules/TelegramApi:TelegramApi#shared",
    	"//submodules/MtProtoKit:MtProtoKit#shared",
    	"//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
    	"//submodules/Postbox:Postbox#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/CloudData:CloudData",
        "//submodules/EncryptionProvider:EncryptionProvider",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
