load("//Config:buck_rule_macros.bzl", "framework")

framework(
    name = "TelegramCore",
    srcs = glob([
        "Sources/*.swift",
    ]),
    deps = [
        "//submodules/TelegramApi:TelegramApi#shared",
    	"//submodules/MtProtoKit:MtProtoKit#shared",
    	"//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
    	"//submodules/Postbox:Postbox#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/CloudData:CloudData",
        "//submodules/EncryptionProvider:EncryptionProvider",
        "//submodules/CryptoUtils:CryptoUtils",
        "//submodules/NetworkLogging:NetworkLogging",
        "//submodules/Reachability:Reachability",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
