load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "UniversalMediaPlayer",
    srcs = glob([
        "Sources/**/*.swift",
        "Sources/*.m",
    ]),
    headers = glob([
        "Sources/*.h",
    ], exclude = ["Sources/UniversalMediaPlayer.h"]),
    exported_headers = glob([
        "Sources/*.h",
    ], exclude = ["Sources/UniversalMediaPlayer.h"]),
    deps = [
    	"//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
    	"//submodules/Postbox:Postbox#shared",
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/TelegramAudio:TelegramAudio",
        "//submodules/FFMpeg:FFMpeg",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
