objc_library(
    name = "EncryptionProvider",
    srcs = glob([
        "Sources/**/*.m",
    ]),
    hdrs = glob([
        "Sources/**/*.h",
    ]),
    includes = [
        "Sources/Public",
    ],
    deps = [
    ],
    visibility = ["//visibility:public"],
)
