
objc_library(
    name = "EncryptionProvider",
    enable_modules = True,
    module_name = "EncryptionProvider",
    srcs = [],
    hdrs = glob([
        "PublicHeaders/**/*.h",
    ]),
    includes = [
        "PublicHeaders",
    ],
    deps = [
    ],
    visibility = ["//visibility:public"],
)
