load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "MessageReactionListUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
    	"//submodules/TelegramCore:TelegramCore#shared",
    	"//submodules/Postbox:Postbox#shared",
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/LocalMediaResources:LocalMediaResources",
        "//submodules/TinyThumbnail:TinyThumbnail",
        "//submodules/ImageBlur:ImageBlur",
        "//submodules/MediaResources:MediaResources",
        "//submodules/PhotoResources:PhotoResources",
        "//submodules/PersistentStringHash:PersistentStringHash",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
