load("//Config:buck_rule_macros.bzl", "framework")

public_headers = glob([
  "Source/PublicHeaders/AsyncDisplayKit/*.h",
])

private_headers = glob([
  "Source/*.h",
])

framework(
  name = "AsyncDisplayKit",
  srcs = glob([
    "Source/**/*.m",
    "Source/**/*.mm",
  ]),
  headers = private_headers,
  exported_headers = public_headers,
  compiler_flags = [
    "-DMINIMAL_ASDK",
  ],
  frameworks = [
    "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    "$SDKROOT/System/Library/Frameworks/QuartzCore.framework",
    "$SDKROOT/System/Library/Frameworks/CoreMedia.framework",
    "$SDKROOT/System/Library/Frameworks/CoreText.framework",
    "$SDKROOT/System/Library/Frameworks/CoreGraphics.framework",
  ]
)
