load("//Config:buck_rule_macros.bzl", "framework")

framework(
    name = "Display",
    srcs = glob([
        "Display/**/*.swift",
        "Display/**/*.m",
    ]),
    headers = glob([
        "Display/*.h",
    ], exclude = ["Display/Display.h"]),
    exported_headers = glob([
        "Display/*.h",
    ], exclude = ["Display/Display.h"]),
    deps = [
    	"//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
    	"//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AppBundle:AppBundle",
        "//submodules/Markdown:Markdown",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
