load("//Config:buck_rule_macros.bzl", "framework")

framework(
    name = "Display",
    srcs = glob([
        "Source/**/*.swift",
    ]),
    deps = [
        "//submodules/ObjCRuntimeUtils:ObjCRuntimeUtils",
        "//submodules/UIKitRuntimeUtils:UIKitRuntimeUtils",
    	"//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
    	"//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AppBundle:AppBundle",
        "//submodules/Markdown:Markdown",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
