load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "FileStorage",
    module_name = "FileStorage",
    srcs = glob([
        "**/*.swift",
    ]),
    visibility = ["//visibility:public"],
    deps = [

    ],
)
