load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "PassportUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/PhoneInputNode:PhoneInputNode",
        "//submodules/CountrySelectionUI:CountrySelectionUI",
        "//submodules/GalleryUI:GalleryUI",
        "//submodules/LegacyComponents:LegacyComponents",
        "//submodules/OverlayStatusController:OverlayStatusController",
        "//submodules/LegacyUI:LegacyUI",
        "//submodules/ImageCompression:ImageCompression",
        "//submodules/DateSelectionUI:DateSelectionUI",
        "//submodules/PasswordSetupUI:PasswordSetupUI",
        "//submodules/AppBundle:AppBundle",
        "//submodules/PresentationDataUtils:PresentationDataUtils",
        "//submodules/Markdown:Markdown",
        "//submodules/PhoneNumberFormat:PhoneNumberFormat",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
