load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "Lottie",
    srcs = glob([
        "lottie-ios/**/*.m",
    ]),
    headers = glob([
    	"lottie-ios/**/*.h",
    ]),
	exported_headers = glob([
    	"lottie-ios/Classes/PublicHeaders/*.h",
    ]),
    deps = [
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
