# This file can be depended upon for any apple_test_lib rules.
genrule(
    name = "test_info_plist",
    visibility = ["PUBLIC"],
    srcs = [
        "BuckSupportFiles/TestInfo.plist",
    ],
    out = 'TestInfo.plist',
    cmd = 'cp $SRCDIR/BuckSupportFiles/TestInfo.plist $OUT',
)
