load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "NGTransitions",
    module_name = "NGTransitions",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [

    ],
    visibility = ["//visibility:public"],

)
