load("//Config:buck_rule_macros.bzl", "static_library")

apple_resource(
    name = "WalletUIResources",
    files = glob([
        "Resources/**/*",
    ], exclude = ["Resources/**/.*"]),
    visibility = ["PUBLIC"],
)

static_library(
    name = "WalletUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/OverlayStatusController:OverlayStatusController",
        "//submodules/AppBundle:AppBundle",
        "//submodules/SolidRoundedButtonNode:SolidRoundedButtonNode",
        "//submodules/UndoUI:UndoUI",
        "//submodules/AlertUI:AlertUI",
        "//submodules/TextFormat:TextFormat",
        "//submodules/Camera:Camera",
        "//submodules/PasscodeInputFieldNode:PasscodeInputFieldNode",
        "//submodules/QrCode:QrCode",
        "//submodules/MergeLists:MergeLists",
        "//submodules/GlassButtonNode:GlassButtonNode",
        "//submodules/UrlHandling:UrlHandling",
        "//submodules/UrlEscaping:UrlEscaping",
        "//submodules/LocalAuth:LocalAuth",
        "//submodules/ScreenCaptureDetection:ScreenCaptureDetection",
	"//submodules/AnimationUI:AnimationUI",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
        "$SDKROOT/System/Library/Frameworks/CoreImage.framework",
    ],
)
