load("//Config:buck_rule_macros.bzl", "static_library")

apple_resource(
    name = "WalletUIResources",
    files = glob([
        "Resources/**/*",
    ], exclude = ["Resources/**/.*"]),
    visibility = ["PUBLIC"],
)

apple_asset_catalog(
    name = 'WalletUIAssets',
    dirs = [
        "WalletImages.xcassets",
    ],
    visibility = ["PUBLIC"],
)

static_library(
    name = "WalletUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/OverlayStatusController:OverlayStatusController",
        "//submodules/AppBundle:AppBundle",
        "//submodules/SolidRoundedButtonNode:SolidRoundedButtonNode",
        "//submodules/AlertUI:AlertUI",
        "//submodules/Camera:Camera",
        "//submodules/QrCode:QrCode",
        "//submodules/MergeLists:MergeLists",
        "//submodules/GlassButtonNode:GlassButtonNode",
        "//submodules/UrlEscaping:UrlEscaping",
        "//submodules/LocalAuth:LocalAuth",
        "//submodules/ScreenCaptureDetection:ScreenCaptureDetection",
        "//submodules/AnimatedStickerNode:AnimatedStickerNode",
        "//submodules/WalletUrl:WalletUrl",
        "//submodules/WalletCore:WalletCore",
        "//submodules/StringPluralization:StringPluralization",
        "//submodules/ActivityIndicator:ActivityIndicator",
        "//submodules/ProgressNavigationButtonNode:ProgressNavigationButtonNode",
        "//submodules/Markdown:Markdown",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
        "$SDKROOT/System/Library/Frameworks/CoreImage.framework",
    ],
)
