load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "WalletUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/OverlayStatusController:OverlayStatusController",
        "//submodules/AppBundle:AppBundle",
        "//submodules/SolidRoundedButtonNode:SolidRoundedButtonNode",
	"//submodules/AccountContext:AccountContext",
	"//submodules/UndoUI:UndoUI",
	"//submodules/AlertUI:AlertUI",
	"//submodules/MergeLists:MergeLists",
	"//submodules/ItemListUI:ItemListUI",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
