load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "WalletCore",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
	    "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/TonBinding:TonBinding",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
