load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "TelegramStringFormatting",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
    	"//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
    	"//submodules/Postbox:Postbox#shared",
	    "//submodules/Display:Display#shared",
    	"//submodules/PlatformRestrictionMatching:PlatformRestrictionMatching",
    	"//submodules/LocalizedPeerData:LocalizedPeerData",
    	"//submodules/TextFormat:TextFormat",
        "//submodules/Markdown:Markdown",
    	"//submodules/TelegramUIPreferences:TelegramUIPreferences",
    	"//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/AppBundle:AppBundle",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
