load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "LocalizedPeerData",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/TelegramUIPreferences:TelegramUIPreferences",
        "//submodules/PhoneNumberFormat:PhoneNumberFormat",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
