load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "LocalizedPeerData",
    srcs = glob([
        "Sources/*.swift",
    ]),
    deps = [
        "//submodules/TelegramCore:TelegramCore#dynamic",
        "//submodules/Postbox:Postbox#dynamic",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/TelegramUIPreferences:TelegramUIPreferences",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
