load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "SwipeToDismissGesture",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
