load("@build_bazel_rules_swift//swift:swift.bzl",
    "swift_library",
)

swift_library(
    name = "LottieSwift",
    module_name = "LottieSwift",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
    ],
    visibility = ["//visibility:public"],
)
