load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "HexColor",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/TextFormat:TextFormat",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
