load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "NGEnv",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/BuildConfig:BuildConfig"
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
