load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "TelegramPresentationData",
    srcs = glob([
        "Sources/**/*.swift",
        "Sources/*.m",
    ]),
    headers = glob([
        "Sources/*.h",
    ], exclude = ["Sources/TelegramPresentationData.h"]),
    exported_headers = glob([
        "Sources/*.h",
    ], exclude = ["Sources/TelegramPresentationData.h"]),
    deps = [
    	"//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
    	"//submodules/Postbox:Postbox#shared",
	    "//submodules/Display:Display#shared",
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
    	"//submodules/TelegramUIPreferences:TelegramUIPreferences",
        "//submodules/MediaResources:MediaResources",
        "//submodules/AppBundle:AppBundle",
        "//submodules/StringPluralization:StringPluralization",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
