load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "PeersNearbyUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/AccountContext:AccountContext",
        "//submodules/TelegramUIPreferences:TelegramUIPreferences",
        "//submodules/ItemListUI:ItemListUI",
        "//submodules/OverlayStatusController:OverlayStatusController",
        "//submodules/DeviceLocationManager:DeviceLocationManager",
        "//submodules/AlertUI:AlertUI",
        "//submodules/PresentationDataUtils:PresentationDataUtils",
        "//submodules/ItemListPeerItem:ItemListPeerItem",
        "//submodules/TelegramPermissionsUI:TelegramPermissionsUI",
        "//submodules/ItemListPeerActionItem:ItemListPeerActionItem",
        "//submodules/PeersNearbyIconNode:PeersNearbyIconNode",
        "//submodules/Geocoding:Geocoding",
        "//submodules/AppBundle:AppBundle",
        "//submodules/AnimatedStickerNode:AnimatedStickerNode",
        "//submodules/TelegramStringFormatting:TelegramStringFormatting",
        "//submodules/TelegramNotices:TelegramNotices",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
        "$SDKROOT/System/Library/Frameworks/MapKit.framework",
    ],
)
