load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "TextFormat",
    srcs = glob([
        "Sources/*.swift",
    ]),
    deps = [
        "//submodules/TelegramCore:TelegramCore#dynamic",
        "//submodules/Display:Display#dynamic",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
