load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "TextFormat",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/Display:Display#shared",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/Markdown:Markdown",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
