load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "PasscodeUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/TelegramUIPreferences:TelegramUIPreferences",
        "//submodules/AccountContext:AccountContext",
        "//submodules/LocalAuth:LocalAuth",
        "//submodules/LegacyComponents:LegacyComponents",
        "//submodules/TelegramStringFormatting:TelegramStringFormatting",
        "//submodules/ImageBlur:ImageBlur",
        "//submodules/AppBundle:AppBundle",
        "//submodules/PasscodeInputFieldNode:PasscodeInputFieldNode",
        "//submodules/MonotonicTime:MonotonicTime",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
