load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "RaiseToListen",
    srcs = glob([
        "Sources/*.swift",
    ]),
    deps = [
        "//submodules/RaiseToListen/Impl:RaiseToListenImpl",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
