load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "NGRequests",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//Nicegram/NGLogging:NGLogging"
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
