load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "ShareController",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
    	"//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
    	"//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
    	"//submodules/Postbox:Postbox#shared",
    	"//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
    	"//submodules/SaveToCameraRoll:SaveToCameraRoll",
    	"//submodules/StickerResources:StickerResources",
    	"//submodules/UrlEscaping:UrlEscaping",
    	"//submodules/LocalizedPeerData:LocalizedPeerData",
    	"//submodules/ActionSheetPeerItem:ActionSheetPeerItem",
    	"//submodules/ChatListSearchRecentPeersNode:ChatListSearchRecentPeersNode",
    	"//submodules/PeerPresenceStatusManager:PeerPresenceStatusManager",
    	"//submodules/SelectablePeerNode:SelectablePeerNode",
    	"//submodules/RadialStatusNode:RadialStatusNode",
    	"//submodules/ActivityIndicator:ActivityIndicator",
        "//submodules/AppBundle:AppBundle",
        "//submodules/TelegramStringFormatting:TelegramStringFormatting",
        "//submodules/TelegramIntents:TelegramIntents",
        "//submodules/AccountContext:AccountContext",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
