/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define LOTTIE_CACHE_SUPPORT 1

#define LOTTIE_IMAGE_MODULE_SUPPORT 1

#define LOTTIE_THREAD_SUPPORT 1

