load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "ActionSheetPeerItem",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
    	"//submodules/AvatarNode",
    	"//submodules/TelegramPresentationData",
        "//submodules/Postbox",
        "//submodules/TelegramCore",
        "//submodules/Display",
        "//submodules/AsyncDisplayKit",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
