load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "SSignalKit",
    srcs = glob([
        "*.m",
    ]),
    headers = glob([
    	"*.h",
    ]),
    exported_headers = glob([
    	"*.h",
    ]),
    deps = [
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
