load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "SSignalKit",
    srcs = glob([
        "Source/SSignalKit/*.m",
    ]),
    exported_headers = glob([
    	"Source/SSignalKit/*.h",
    ]),
    deps = [
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
