
objc_library(
    name = "SSignalKit",
    enable_modules = True,
    module_name = "SSignalKit",
    srcs = glob([
        "Source/SSignalKit/*.m",
    ]),
    copts = [
        "-Werror",
    ],
    hdrs = glob([
        "Source/SSignalKit/*.h",
    ]),
    includes = [
      "Source",
    ],
    sdk_frameworks = [
      "Foundation",
    ],
    visibility = [
        "//visibility:public",
    ],
)
