load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "TelegramUIPreferences",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
    	"//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
    	"//submodules/Postbox:Postbox#shared",
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/Display:Display#shared",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
