load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "CloudData",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/MtProtoKit:MtProtoKit#shared",
        "//submodules/EncryptionProvider:EncryptionProvider",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
    weak_frameworks = [
        "CloudKit",
    ],
)
