load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "EncryptionKeyVisualization",
    srcs = glob([
        "Sources/*.swift",
        "Sources/*.m",
    ]),
    headers = glob([
        "Sources/*.h",
    ], exclude = ["Sources/EncryptionKeyVisualization.h"]),
    exported_headers = glob([
        "Sources/*.h",
    ], exclude = ["Sources/EncryptionKeyVisualization.h"]),
    deps = [
    	"//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
