load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "EncryptionKeyVisualization",
    srcs = glob([
        "Sources/*.swift",
    ]),
    deps = [
    	"//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/EncryptionKeyVisualization/Impl:EncryptionKeyVisualizationImpl",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
