load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "GalleryUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/TextFormat:TextFormat",
        "//submodules/AccountContext:AccountContext",
        "//submodules/TelegramUniversalVideoContent:TelegramUniversalVideoContent",
        "//submodules/WebsiteType:WebsiteType",
        "//submodules/ScreenCaptureDetection:ScreenCaptureDetection",
        "//submodules/OpenInExternalAppUI:OpenInExternalAppUI",
        "//submodules/ShareController:ShareController",
        "//submodules/SwipeToDismissGesture:SwipeToDismissGesture",
        "//submodules/CheckNode:CheckNode",
        "//submodules/AppBundle:AppBundle",
        "//submodules/StickerPackPreviewUI:StickerPackPreviewUI",
        "//submodules/OverlayStatusController:OverlayStatusController",
        "//submodules/PresentationDataUtils:PresentationDataUtils",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
        "$SDKROOT/System/Library/Frameworks/QuickLook.framework",
        "$SDKROOT/System/Library/Frameworks/SafariServices.framework",
    ],
)
