load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "ChatListSearchRecentPeersNode",
    srcs = glob([
        "Sources/*.swift",
    ]),
    deps = [
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
