load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "Stripe",
    srcs = glob([
        "Sources/*.m",
    ]),
    headers = glob([
        "Sources/*.h",
    ], exclude = ["Sources/Stripe.h"]),
    exported_headers = [
        "Sources/STPAddress.h",
        "Sources/STPPaymentCardTextField.h",
        "Sources/STPAPIClient.h",
        "Sources/STPAPIClient+ApplePay.h",
        "Sources/STPAPIResponseDecodable.h",
        "Sources/STPPaymentConfiguration.h",
        "Sources/STPCard.h",
        "Sources/STPCardBrand.h",
        "Sources/STPCardParams.h",
        "Sources/STPToken.h",
        "Sources/STPBankAccount.h",
        "Sources/STPBankAccountParams.h",
        "Sources/STPBINRange.h",
        "Sources/STPCardValidator.h",
        "Sources/STPCardValidationState.h",
        "Sources/STPCustomer.h",
        "Sources/STPFormEncodable.h",
        "Sources/STPPaymentMethod.h",
        "Sources/STPPhoneNumberValidator.h",
        "Sources/STPPostalCodeValidator.h",
        "Sources/STPSource.h",
        "Sources/STPBlocks.h",
        "Sources/StripeError.h",
        "Sources/STPBackendAPIAdapter.h",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
