XCODE_BINARY_CONFIG = {
    'IPHONEOS_DEPLOYMENT_TARGET': '8.0',
    'SDKROOT': 'iphoneos',
    'GCC_OPTIMIZATION_LEVEL': '0',
    'SWIFT_OPTIMIZATION_LEVEL': '-Onone',
    'SWIFT_WHOLE_MODULE_OPTIMIZATION': 'NO',
    'ONLY_ACTIVE_ARCH': 'YES',
    'LD_RUNPATH_SEARCH_PATHS': '@executable_path/Frameworks',
}

XCODE_STATIC_LIBRARY_CONFIG = {
    'SKIP_INSTALL': 'YES',
}
