load("//Config:buck_rule_macros.bzl", "static_library", "framework")

framework(
    name = "Emoji",
    srcs = glob([
        "Sources/*.swift",
    ]),
    deps = [
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/CoreText.framework",
        "$SDKROOT/System/Library/Frameworks/AVFoundation.framework",
    ],
)
