load("//Config:buck_rule_macros.bzl", "static_library", "glob_map", "glob_sub_map", "merge_maps")

static_library(
    name = "TgVoipWebrtcCustom",
    srcs = glob([
        "Sources/**/*.m",
        "Sources/**/*.mm",
        "Impl/*.cpp",
    ]),
    has_cpp = True,
    headers = merge_maps([
        glob_sub_map("PublicHeaders/", [
            "PublicHeaders/**/*.h",
        ]),
        glob_sub_map("Impl/", [
            "Impl/*.h",
        ]),
    ]),
    exported_headers = glob([
        "PublicHeaders/**/*.h",
    ]),
    compiler_flags = [
        "-Ithird-party/submodules/TgVoipWebrtcCustom/PublicHeaders",
        "-Ithird-party/webrtc/webrtc-ios/src",
        "-Ithird-party/webrtc/webrtc-ios/src/third_party/abseil-cpp",
        "-Ithird-party/webrtc/webrtc-ios/src/sdk/objc",
        "-Ithird-party/webrtc/webrtc-ios/src/sdk/objc/base",
        "-Ithird-party/webrtc/webrtc-ios/src/sdk/objc/components/renderer/metal",
        "-DWEBRTC_IOS",
        "-DWEBRTC_MAC",
        "-DWEBRTC_POSIX",
        "-std=c++14",
    ],
    deps = [
        "//third-party/webrtc:webrtc_lib",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
        "$SDKROOT/System/Library/Frameworks/AudioToolbox.framework",
        "$SDKROOT/System/Library/Frameworks/VideoToolbox.framework",
        "$SDKROOT/System/Library/Frameworks/CoreTelephony.framework",
        "$SDKROOT/System/Library/Frameworks/CoreMedia.framework",
        "$SDKROOT/System/Library/Frameworks/AVFoundation.framework",
        "$SDKROOT/System/Library/Frameworks/Metal.framework",
    ],
)
