load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "ShareItems",
    srcs = glob([
        "Sources/**/*.swift",
        "Sources/*.m",
    ]),
    headers = glob([
        "Sources/*.h",
    ], exclude = ["Sources/ShareItems.h"]),
    exported_headers = glob([
        "Sources/*.h",
    ], exclude = ["Sources/ShareItems.h"]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/MtProtoKit:MtProtoKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/LegacyComponents:LegacyComponents",
        "//submodules/LocalMediaResources:LocalMediaResources",
        "//submodules/Pdf:Pdf",
        "//submodules/AccountContext:AccountContext",
        "//submodules/MimeTypes:MimeTypes",
        "//submodules/PhoneNumberFormat:PhoneNumberFormat",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
