load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "LiveLocationManager",
    srcs = glob([
        "Sources/*.swift",
    ]),
    deps = [
    	"//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#dynamic",
        "//submodules/TelegramCore:TelegramCore#dynamic",
        "//submodules/Postbox:Postbox#dynamic",
        "//submodules/DeviceLocationManager:DeviceLocationManager",
        "//submodules/AccountContext:AccountContext",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/CoreLocation.framework",
    ],
)
