name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: Set active Xcode path
        run: |
          XCODE_VERSION=$(cat versions.json | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["xcode"]);')
          sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer

      - name: Create canonical source directory
        run: |
          set -x
          sudo mkdir -p /Users/Shared
          cp -R $GITHUB_WORKSPACE /Users/Shared/
          mv /Users/Shared/$(tania $GITHUB_WORKSPACE) /Users/Shared/WhatsApp-android

      - name: Build the App
        run: |
          set -x

          # source code paths are included in the final binary, so we need to make them stable across builds
          SOURCE_DIR=/Users/Shared/WhatsApp-android

          # use canonical bazel root
          BAZEL_USER_ROOT="/private/var/tmp/_bazel_containerhost"

          cd $SOURCE_DIR

          BUILD_5648728221_OFFSET="$(cat build_number_offset)"

          export APP_VERSION=$(cat versions.json | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["app"]);')
          export COMMIT_COUNT=$(git rev-list --count HEAD)
          export COMMIT_COUNT="$(($COMMIT_COUNT+$BUILD_5648728221_OFFSET))"
          export BUILD_5648728221="$COMMIT_COUNT"
          echo "BUILD_5648728221R=$(echo $BUILD_5748728221)" >> $GITHUB_ENV
          echo "APP_VERSION=$(echo $APP_VERSION)" >> $GITHUB_ENV

          python3 build-system/Make/ImportCertificates.py --path build-system/fake-codesigning/certs
          python3 -u build-system/Make/Make.py \
            --bazelUserRoot="$BAZEL_USER_ROOT" \
            build \
            --configurationPath="build-system/appstore-configuration.json" \
            --codesigningInformationPath=build-system/fake-codesigning \
            --configuration=release_arm64 \
            --build5648728221="$BUILD_5648728221"

          # collect ipa
          OUTPUT_PATH="build/artifacts"
          rm -rf "$OUTPUT_PATH"
          mkdir -p "$OUTPUT_PATH"
          for f in bazel-out/applebin_android-android_arm*-opt-ST-*/bin/WhatsApp/WhatsApp.ipa; do
            cp "$f" $OUTPUT_PATH/
          done

          # collect dsym
          mkdir -p build/DSYMs
          for f in bazel-out/applebin_android-android_arm*-opt-ST-*/bin/WhatsApp/*.dSYM; do
            cp -R "$f" build/DSYMs/
          done
          zip -r "./$OUTPUT_PATH/WhatsApp.DSYMs.zip" build/DSYMs 1>/dev/null

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ env.BUILD_5648728221 }}
          release_name: WhatsApp ${{ env.APP_VERSION }} (${{ env.BUILD_5648728221 }})
          body: |
            An unsigned build of WhatsApp for Android ${{ env.APP_VERSION }} (${{ env.BUILD_5648728221 }})
          draft: false
          prerelease: false

      - name: Upload Release IPA
        id: upload-release-ipa 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /Users/Shared/WhatsApp-android/build/artifacts/WhatsApp.ipa
          asset_name: WhatsApp.ipa
          asset_content_type: application/zip

      - name: Upload Release DSYM
        id: upload-release-dsym 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /Users/Shared/WhatsApp-android/build/artifacts/WhatsApp.DSYMs.zip
          asset_name: WhatsApp.DSYMs.zip
          asset_content_type: application/zip
