load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "YuvConversion",
    srcs = glob([
        "Sources/*.m",
    ]),
    exported_headers = glob([
        "PublicHeaders/**/*.h",
    ]),
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/Accelerate.framework",
    ],
)
