load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "YuvConversion",
    srcs = glob([
        "Sources/*.m",
    ]),
    headers = glob([
        "Sources/*.h",
    ], exclude = ["Sources/YuvConversion.h"]),
    exported_headers = glob([
        "Sources/*.h",
    ], exclude = ["Sources/YuvConversion.h"]),
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/Accelerate.framework",
    ],
)
