load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "ImageBlur",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//submodules/FastBlur:FastBlur",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
        "$SDKROOT/System/Library/Frameworks/Accelerate.framework",
    ],
)
